<?php

namespace App\Repository;

use App\Entity\OperatingSystem;
use App\Model\Dockerfile\Image;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;

/**
 * OperatingSystemRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class OperatingSystemRepository extends EntityRepository
{
    /**
     * @param Image $image
     * @return OperatingSystem|null
     */
    public function findOneByImage(Image $image)
    {
        $qb = $this->createQueryBuilder('os');
        $qb->leftJoin('os.imageConfigs', 'i');
        $qb->where('i.id = :image');
        $qb->setParameter('image', $image);
        $qb->setMaxResults(1);

        try {
            return $qb->getQuery()->getOneOrNullResult();
        } catch (NonUniqueResultException $exception) {
            return null;
        }
    }
}
